// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `blue.2048` namespace.
pub mod defs;
pub mod game;
pub mod key;
pub mod player;
pub mod verification;
#[derive(Debug)]
pub struct Game;
impl atrium_api::types::Collection for Game {
    const NSID: &'static str = "blue.2048.game";
    type Record = game::Record;
}
