// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `blue.2048.key.player` namespace.
pub mod stats;
#[derive(Debug)]
pub struct Stats;
impl atrium_api::types::Collection for Stats {
    const NSID: &'static str = "blue.2048.key.player.stats";
    type Record = stats::Record;
}
