// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `blue.2048.verification.defs` namespace.
//!Reusable types for an at://2048 authority to prove that it has verified a record
///Holds the signature for another record showing it has verified it to the best of it's ability and it should be trusted if the signatures match.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct VerificationRefData {
    pub created_at: atrium_api::types::string::Datetime,
    ///The at://uri for the public did:key to verify the remote record. This also counts as the authority of the verification (example @2048.blue). As well as the type of verification by the collection name (blue.2048.key.game).
    pub key_ref: String,
    ///The at://uri for the record that is being verified.
    pub record_ref: String,
    ///The public verifiable signature of the record. Serialization of the records valued
    pub signature: String,
    ///DID of the subject the verification applies to.
    pub subject: atrium_api::types::string::Did,
}
pub type VerificationRef = atrium_api::types::Object<VerificationRefData>;
