// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `blue.2048.player` namespace.
pub mod profile;
pub mod stats;
#[derive(Debug)]
pub struct Profile;
impl atrium_api::types::Collection for Profile {
    const NSID: &'static str = "blue.2048.player.profile";
    type Record = profile::Record;
}
#[derive(Debug)]
pub struct Stats;
impl atrium_api::types::Collection for Stats {
    const NSID: &'static str = "blue.2048.player.stats";
    type Record = stats::Record;
}
