// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `blue.2048.verification` namespace.
pub mod defs;
pub mod game;
pub mod stats;
#[derive(Debug)]
pub struct Game;
impl atrium_api::types::Collection for Game {
    const NSID: &'static str = "blue.2048.verification.game";
    type Record = game::Record;
}
#[derive(Debug)]
pub struct Stats;
impl atrium_api::types::Collection for Stats {
    const NSID: &'static str = "blue.2048.verification.stats";
    type Record = stats::Record;
}
